# Generated by Django 5.1.5 on 2025-01-21 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis', models.CharField(max_length=50)),
                ('kode_jenis', models.IntegerField()),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jenis',
            },
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_level', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'level',
            },
        ),
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pegawai', models.CharField(max_length=50)),
                ('nip', models.IntegerField(unique=True)),
                ('alamat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pegawai',
            },
        ),
        migrations.CreateModel(
            name='ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruang', models.CharField(max_length=30)),
                ('kode_ruang', models.IntegerField(unique=True)),
                ('keterangan', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ruang',
            },
        ),
        migrations.CreateModel(
            name='inventaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kondisi', models.CharField(max_length=50)),
                ('keterangan', models.CharField(max_length=50)),
                ('tanggal_register', models.DateField()),
                ('kode_inventaris', models.IntegerField(unique=True)),
                ('id_jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.jenis')),
            ],
            options={
                'db_table': 'inventaris',
            },
        ),
        migrations.CreateModel(
            name='peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('status_peminjaman', models.CharField(max_length=20)),
                ('id_pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pegawai')),
            ],
            options={
                'db_table': 'peminjaman',
            },
        ),
        migrations.CreateModel(
            name='detail_pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('id_invetaris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.inventaris')),
                ('id_peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.peminjaman')),
            ],
            options={
                'db_table': 'detail_pinjam',
            },
        ),
        migrations.CreateModel(
            name='petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('nama_petugas', models.CharField(max_length=100)),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.level')),
            ],
            options={
                'db_table': 'petugas',
            },
        ),
        migrations.AddField(
            model_name='inventaris',
            name='id_petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.petugas'),
        ),
        migrations.AddField(
            model_name='inventaris',
            name='id_ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.ruang'),
        ),
    ]
