# Generated by Django 5.1.5 on 2025-02-06 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis', models.CharField(max_length=50)),
                ('kode_jenis', models.IntegerField()),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jenis',
            },
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_level', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'level',
            },
        ),
        migrations.CreateModel(
            name='ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruang', models.CharField(max_length=30)),
                ('kode_ruang', models.IntegerField(unique=True)),
                ('keterangan', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ruang',
            },
        ),
        migrations.CreateModel(
            name='inventaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kondisi', models.CharField(max_length=50)),
                ('keterangan', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField()),
                ('tanggal_register', models.DateField()),
                ('kode_inventaris', models.CharField(max_length=20)),
                ('id_jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.jenis')),
                ('id_ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.ruang')),
            ],
            options={
                'db_table': 'inventaris',
            },
        ),
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nama_pegawai', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('alamat', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, related_name='pegawai_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='pegawai_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'pegawai',
            },
        ),
        migrations.CreateModel(
            name='peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status_peminjaman', models.CharField(default='Dipinjam', max_length=20)),
                ('id_pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pegawai')),
            ],
            options={
                'db_table': 'peminjaman',
            },
        ),
        migrations.CreateModel(
            name='detail_pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('kondisi', models.CharField(blank=True, choices=[('baik', 'Baik'), ('rusak', 'Rusak'), ('hilang', 'Hilang')], max_length=10, null=True)),
                ('id_inventaris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.inventaris')),
                ('peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.peminjaman')),
            ],
            options={
                'db_table': 'detail_pinjam',
            },
        ),
        migrations.CreateModel(
            name='petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nama_petugas', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='petugas_groups', to='auth.group')),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.level')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='petugas_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'petugas',
            },
        ),
        migrations.AddField(
            model_name='inventaris',
            name='id_petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
